python -u main.py -s 0001.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0001.HK.log 2>&1
python -u main.py -s 0012.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0012.HK.log 2>&1
python -u main.py -s 0016.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0016.HK.log 2>&1
python -u main.py -s 0002.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0002.HK.log 2>&1
python -u main.py -s 0003.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0003.HK.log 2>&1
python -u main.py -s 0006.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0006.HK.log 2>&1
python -u main.py -s 0005.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0005.HK.log 2>&1
python -u main.py -s 0011.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0011.HK.log 2>&1
python -u main.py -s 2388.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/2388.HK.log 2>&1
python -u main.py -s 0013.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0013.HK.log 2>&1
python -u main.py -s 0762.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0762.HK.log 2>&1
python -u main.py -s 0941.HK -i ./data/processed -o ./results/LMFinance --lexicon LMFinance >results/LMFinance/0941.HK.log 2>&1